version: '2'
services:
  zookeeper:
    container_name: zookeeper
    build: 
      context: .
    command: /kafka/bin/zookeeper-server-start.sh /config/zookeeper
  broker1: 
      container_name: broker1
      depends_on:
        - zookeeper
      build: 
        context: .
      command: /kafka/bin/kafka-server-start.sh /config/broker1
      volumes:
        - ./config:/config
        - ./data/broker1:/data
      ports:
        - 9092:9092
  broker2:
      container_name: broker2
      depends_on:
        - zookeeper
      build: 
        context: .
      command: /kafka/bin/kafka-server-start.sh /config/broker2
      volumes:
        - ./config:/config
        - ./data/broker2:/data
      ports:
        - 9093:9093

  consumer:
      container_name: consumer
      build: 
        context: .
      command: tail -f /dev/null
  producer:
      container_name: producer
      build: 
        context: .
      command: tail -f /dev/null
  operations:
      container_name: operations
      build: 
        context: .
      command: tail -f /dev/null
  