version: '2'
services:
  zookeeper:
    build: 
      context: .
    command: /kafka/bin/zookeeper-server-start.sh /config/zookeeper
  broker1: 
      depends_on:
        - zookeeper
      build: 
        context: .
      command: /kafka/bin/kafka-server-start.sh /config/broker1
      volumes:
        - ./data/broker1:/data
  broker2:
      depends_on:
        - zookeeper
      build: 
        context: .
      command: /kafka/bin/kafka-server-start.sh /config/broker2
      volumes:
        - ./data/broker2:/data
  broker3:
      depends_on:
        - zookeeper
      build: 
        context: .
      command: /kafka/bin/kafka-server-start.sh /config/broker3
      volumes:
        - ./data/broker3:/data
  consumer:
      container_name: consumer
      build: 
        context: .
      command: tail -f /dev/null
  producer:
      container_name: producer
      build: 
        context: .
      command: tail -f /dev/null
  operations:
      container_name: operations
      build: 
        context: .
      command: tail -f /dev/null
  