version: '3'
services:
  zookeeper:
    container_name: zookeeper
    build: 
      context: .
    command: ["/kafka/bin/zookeeper-server-start.sh", "/config/zookeeper"]
    volumes:
      - ./config:/config
      - ./data/zookeeper:/data/zookeeper
  broker1: 
      container_name: broker1
      depends_on:
        - zookeeper
      build: 
        context: .
      command: ["/kafka/bin/kafka-server-start.sh", "/config/broker1"]
      volumes:
        - ./config:/config
        - ./data/broker1:/data/kafka-logs
  broker2:
      container_name: broker2
      depends_on:
        - zookeeper
      build: 
        context: .
      command: ["/kafka/bin/kafka-server-start.sh", "/config/broker2"]
      volumes:
        - ./config:/config
        - ./data/broker2:/data/kafka-logs

  broker3:
      container_name: broker3
      depends_on:
        - zookeeper
      build: 
        context: .
      command: ["/kafka/bin/kafka-server-start.sh", "/config/broker3"]
      volumes:
        - ./config:/config
        - ./data/broker3:/data/kafka-logs