version: '3'
services:
  tools:
    container_name: tools
    build: 
      context: .
    command: ['bash']
    volumes:
      - ./config:/config

  producer:
    container_name: producer
    image: node
    working_dir: /app
    command: ["node", "index.js"]
    volumes:
      - ./src/producer/:/app